{{- if or (.Values.extraConfigMapJson) (.Values.extraConfigMap) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "service.fullname" . }}-config
  namespace: {{ .Values.namespace | default "default" }}
data:
  {{- range $key, $value := .Values.extraConfigMapJson }}
  {{$key}}: |
    {{ . | toJson }}
  {{- end }}

  {{- range $key, $value := .Values.extraConfigMap }}
  {{ $key }}: |
    {{- $value | nindent 4 }}
  {{- end }}
{{- end }}

