---
{{- range $name, $value := .Values.cronjob}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $value.nameOverwrite | default $name }}
  namespace: {{ $.Values.namespace | default "default" }}
spec:
  schedule: {{ required "Required value missing: 'schedule'" $value.schedule | quote }}
  concurrencyPolicy: {{ $value.concurrencyPolicy | default "Forbid"}}
  {{- if ($value.startingDeadlineSeconds) }}
  startingDeadlineSeconds: {{ $value.startingDeadlineSeconds }}
  {{- end }}
  {{- if ($value.successfulJobsHistoryLimit) }}
  successfulJobsHistoryLimit: {{ $value.successfulJobsHistoryLimit }}
  {{- end }}
  {{- if ($value.failedJobsHistoryLimit) }}
  failedJobsHistoryLimit: {{ $value.failedJobsHistoryLimit }}
  {{- end }}
  jobTemplate:
    spec:
      {{- if ($value.parallelism) }}
      parallelism: {{ $value.parallelism }}
      {{- end }}
      {{- if ($value.completions) }}
      completions: {{ $value.completions }}
      {{- end }}
      {{- if ($value.backoffLimit) }}
      backoffLimit: {{ $value.backoffLimit }}
      {{- end }}
      {{- if ($value.activeDeadlineSeconds) }}
      activeDeadlineSeconds: {{ $value.activeDeadlineSeconds }}
      {{- end }}
      template:
        spec:
          containers:
          - name: {{ $value.nameOverwrite | default $name }}
            image: "{{ $value.image.repository }}:{{ $value.image.tag }}"
            imagePullPolicy: {{ $value.image.pullPolicy | default "IfNotPresent" }}
            env: {{ if (not $value.env) }}[]{{ end }}

            {{- range $envKey, $envValue := $value.env }}
            - name: {{ $envKey }}
              {{- if (not $envValue.type) }}
              value: {{ $envValue.value | quote }}
              {{- else if eq $envValue.type "fieldPath" }}
              valueFrom:
                fieldRef:
                  fieldPath: {{ $envValue.value }}
              {{- else if eq $envValue.type "secretKeyRef" }}
              valueFrom:
                secretKeyRef:
                  key: {{ $envValue.key }}
                  name: {{ $envValue.name }}
              {{- else if eq $envValue.type "configMapKeyRef" }}
              valueFrom:
                configMapKeyRef:
                  key: {{ $envValue.key }}
                  name: {{ $envValue.name }}
              {{- end }}
            {{- end }}
            {{- if ($value.envFrom) }}
            {{- if ($value.envFrom.configMapRef)}}
            envFrom:
            {{- range $value.envFrom.configMapRef}}
            - configMapRef:
                name: {{ . }}
            {{- end }}
            {{- end }}
            {{- end }}
            command: [
              {{- range $index, $cmd := $value.commands }}
              {{- if $index }},{{- end }}
              {{ $cmd | quote }}
              {{- end }}
            ]
            args: [
              {{- range $index, $arg := $value.args }}
              {{- if $index }},{{- end }}
              {{ $arg | quote }}
              {{- end }}
            ]
            {{- if or ($value.configMapMountPaths) ($value.extraVolumeMounts) }}
            volumeMounts:
            {{- end }}
            {{- range $key, $value := $value.configMapMountPaths }}
              - mountPath: {{ $value.configMapMountPath }}
                name: configmap
                {{- if ($value.configMapMountSubPath) }}
                subPath: {{ $value.configMapMountSubPath }}
                {{- end }}
            {{- end }}
            {{- range $key, $value := $value.extraVolumeMounts }}
              - mountPath: {{ $value.mountPath }}
                name: {{ $key }}
            {{- end }}
          restartPolicy: {{ $value.restartPolicy | default "OnFailure" }}
          {{- if ($value.terminationGracePeriodSeconds) }}
          terminationGracePeriodSeconds: {{ $value.terminationGracePeriodSeconds }}
          {{- end }}
          {{- if or ($value.configMapMountPaths) ($value.extraVolumeMounts) }}
          volumes:
            - name: configmap
              configMap:
                name: {{ include "service.fullname" $ }}-config
          {{- end }}
          {{- range $key, $value := $value.extraVolumes }}
            - name: {{$key}}
              {{- tpl . $ | nindent 14 -}}
          {{- end }}
---
{{- end }}