{{- if .Values.prometheusRules.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "service.fullname" . }}
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
    release: {{ .Values.prometheusRules.release | default "prometheus" }}
spec:
  groups:
    - name: {{ include "service.fullname" . }}
      rules:
        {{- toYaml .Values.prometheusRules.rules | nindent 6 }}
{{- end }}
