---
{{- range $name, $value := .Values.pvc}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $name }}
  {{- if ($value.namespace) }}
  namespace: {{ $value.namespace  }}
  {{- end }}
spec:
  accessModes:
    - {{$value.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{$value.request | default "2Gi" }}
  storageClassName: {{$value.storageclass}}
---
{{- end }}


