{{- range $name, $value := .Values.sealedSecret}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ $name }}
  {{- if ($.Values.namespace) }}
  namespace: {{ $.Values.namespace  }}
  {{- end }}
spec:
  encryptedData:
    {{ if $value.encryptedData }}
    {{- range $key, $secrect := $value.encryptedData}}
    {{ $key }}: {{ $secrect }}
    {{- end }}
    {{- else -}}
    #prevent validation error of required field when no encrypted data is specified
    dummy-key:
    {{- end }}
  template:
    data:
      {{- range $key, $data := $value.data}}
      {{- if and (kindIs "string" $data) (contains "\n" $data) }}
      {{ $key }}: |
        {{- $data | nindent 8}}
      {{- else }}
      {{ $key }}: {{ $data | toJson }}
      {{- end }}
      {{- end }}
    metadata:
      creationTimestamp: null
      name: {{ $name }}
      namespace: {{ $.Values.namespace | default "default" }}
      {{- with $value.annotations }}
      annotations:
{{- toYaml . | nindent 8 }}
      {{- end }}
    type: {{ $value.type | default "Opaque" }}
---
{{- end }}