{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.fullname" . }}
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
      {{- if (.Values.service.nodePort)}}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}

    {{- range $key, $value := .Values.service.extraPorts }}
    - port: {{ $value.port }}
      targetPort: {{ $value.targetPort }}
      protocol: {{ $value.protocol | default "TCP" }}
      name: {{ $key }}
      {{- if ($value.nodePort) }}
      nodePort: {{ $value.nodePort }}
      {{- end }}
    {{- end }}
  selector:
    {{- include "service.selectorLabels" . | nindent 4 }}
{{- end}}