name: Generate readme and push
on:
  push:
    branches: [ master ]
    
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create report file
        working-directory: ./service/documentation/
        run: ./createReadme.sh
      - name: Commit report
        run: |
          git config --global user.name 'ReadmeBot'
          git add -A
          git commit -am "Automated report"
          git push
